// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdjjkIO6qI3Day0yASRIx9FrAwpdniJpw',
    appId: '1:545685942426:web:5220e0cb962d2a94706f23',
    messagingSenderId: '545685942426',
    projectId: 'camo-chat',
    authDomain: 'camo-chat.firebaseapp.com',
    storageBucket: 'camo-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHGdkL6ZgikuRB4ZIh9FqrvNzwnOOFnBU',
    appId: '1:545685942426:android:2fecd2836888401d706f23',
    messagingSenderId: '545685942426',
    projectId: 'camo-chat',
    storageBucket: 'camo-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU8hSzeh5p8QP0y8KkFwkzMmx9tMIavgE',
    appId: '1:545685942426:ios:e8f7efdac41334af706f23',
    messagingSenderId: '545685942426',
    projectId: 'camo-chat',
    storageBucket: 'camo-chat.appspot.com',
    androidClientId: '545685942426-fv4o8mk2hbststfg816p9i38eunumgcu.apps.googleusercontent.com',
    iosClientId: '545685942426-5jn1lpfhkhrrvbq9f6v33deqrmpdtqua.apps.googleusercontent.com',
    iosBundleId: 'com.example.camoChatMod',
  );
}
